### ISSUE TITLE
Cannot send email through help desk

### ISSUE THREAD

**Issue by olisterr** [frappe/helpdesk#1440]
Hi Frappe Team,
I have setup helpdesk with erpnext.
I'm able to send the email from erpnext but get the error below from helpdesk.

Kindly advise!
![image](https://github.com/frappe/helpdesk/assets/35020704/3f455d6b-6b70-4562-85a2-f69495e09b78)

**Comment by ssiyad** [comment]
Do you have a default outgoing email set up? Also, which version are you on? Provide more context

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists

**Comment by jlxq0** [comment]
I have the same problem: I can send mails from anywhere in ERPNext except for help desk.

I do NOT have a "default outgoing" set; I do instead have ENV vars in the Site Config of Frappe cloud and that seems to work fine everywhere else.

I do it like this, because I want to use a generic SMTP server and credentials for everything, independent of mail boxes or users and could not figure out how else to do that.

Any hints for either problem?
