### ISSUE TITLE
Duplicate entry Helpdesk for key PRIMARY

### ISSUE THREAD

**Issue by ajiragroup** [frappe/helpdesk#1548]
I tried to install Helpdesk in exiting ERPNext instance.

I encountered these errors while running get-app helpdesk.
![image](https://github.com/frappe/helpdesk/assets/108009061/ba14456e-4132-413d-b0a9-a8c545057a49)

While install-app helpdesk, 
![image](https://github.com/frappe/helpdesk/assets/108009061/5be2edd3-71a6-4fbb-8018-85c3161260b2)
![image](https://github.com/frappe/helpdesk/assets/108009061/3df9e905-3b95-406a-921d-c53d0b937c73)

When trying to install again, 
![image](https://github.com/frappe/helpdesk/assets/108009061/4529a86a-bae8-4807-98b0-55819174ba50)

I tried to remove app helpdesk, it says:

`App helpdesk not installed on Site example.com`

Trying to install again give the same previous error : `Duplicate entry 'Helpdesk' for key 'PRIMARY`

**Comment by ssiyad** [comment]
First error happens probably because you need version 14 or develop (latest of either). Posthog is required. I don't know how you are able to install the app if even `get` fails. It also complains about the first issue (Posthog) btw. Third error might be a result of incomplete installation (step 2).

You can try
- Remove the app
- Update frappe
- Or switch to develop (version 15)
- Reinstall/Get
